name: tp_dropdown_2list
description: A customizable dropdown widget for Flutter that supports dual-category item selection with both single and multi-select capabilities.
version: 1.0.0
homepage: https://github.com/pradoui/tp_dropdown_2list
repository: https://github.com/pradoui/tp_dropdown_2list
issue_tracker: https://github.com/pradoui/tp_dropdown_2list/issues
documentation: https://github.com/pradoui/tp_dropdown_2list#readme

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
